### ISSUE TITLE
Unable to load data stream

### ISSUE THREAD

**Issue by ced1459** [mkvd/smarttv-twitch#60]
Just installed the app. After opening it, after 15 "retrying" I get this message "Unable to load data stream". Anyone else?

**Comment by Pet-Fly** [comment]
I have the same issue. I've been searching left and right but still can't find a solution.

**Comment by ced1459** [comment]
Thank you it's working now. However I'm getting "low/medium/high quality is not supported by your device, try source quality" The only way to make it work is to set the quality to auto (since source isn't working too). I wish I could lower the quality a little since it gets some loading spike once in a while, but I guess that will do for now.

**Comment by Pet-Fly** [comment]
Many people seem to have such problems (myself included). I installed this app mostly to watch a few StarCraft 2 channels and none of them is working... tough luck.

But the developer of the app has already responded to questions like that, stating that the issue is not in the app, but in the TVs.

You can check issue #39 for example.

**Comment by ced1459** [comment]
Today auto wasn't even working... A big let down from Samsung to not support a Twitch app in my opinion. Thank you for your answers.
